### ISSUE TITLE
Can't login - Region Issue?

### ISSUE THREAD

**Issue by Jemzlel** [ndg63276/smartathome#7]
Trying to log in and tried each region and doesn't work.

I am AU region if that makes any difference.

Also reset password to just numbers and letters, only has a capital letter

**Comment by ndg63276** [comment]
Make sure your credentials work in the Smart Life app ([iOS](https://apps.apple.com/us/app/smart-life-smart-living/id1115101477) or [Android](https://play.google.com/store/apps/details?id=com.tuya.smartlife&hl=en&gl=US)), it seems that credentials from the Tuya app don't work.

**Comment by Jemzlel** [comment]
Hey there, that seemed to work, I had signed up using the brilliantsmart app. Created account with smartlife, then removed device from brilliantsmart, re-added in smartlife then login worked
